name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o tgreport-linux-amd64

      - name: Build Darwin (macOS) binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o tgreport-darwin-amd64

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tgreport-linux-amd64
            tgreport-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 